/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Dashboard.Menu;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ouka
 */
public class Gerbong_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Gerbong
     */
    public Gerbong_Menu() {
        initComponents();
        tbGerbong.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbGerbong.setOpaque(false);
        tbGerbong.getTableHeader().setBackground(new Color(0,74,163));
        tbGerbong.getTableHeader().setForeground(new Color(255,255,255));
        tbGerbong.setRowHeight(25);
        txtIDKeretaGerbong.setEditable(false);
        btnUpdateGerbong.setEnabled(false);
        btnDeleteGerbong.setEnabled(false);
        btnUpdateGerbong.setFocusPainted(false);
        btnInsertGerbong.setFocusPainted(false);
        btnDeleteGerbong.setFocusPainted(false);
        btnResetGerbong.setFocusPainted(false);
        this.setLocationRelativeTo(null);
    }
    
    public void setID_Kereta(String id_kereta){
        txtIDKeretaGerbong.setText(id_kereta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGerbong = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIDKeretaGerbong = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtID_Gerbong = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtNomorGerbong = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtKapasitasGerbong = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnInsertGerbong = new javax.swing.JButton();
        btnUpdateGerbong = new javax.swing.JButton();
        btnDeleteGerbong = new javax.swing.JButton();
        btnResetGerbong = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnNextGerbong = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnFirstGerbong = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnLastGerbong = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnPrevGerbong = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 30, 84));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/multiply_15px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/database_administrator_60px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Daftar Gerbong");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 42, 113));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbGerbong.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbGerbong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "ID Kereta", "ID Gerbong", "Nomor", "Kapasitas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGerbong.setFocusable(false);
        tbGerbong.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbGerbong.setRowHeight(25);
        tbGerbong.setSelectionBackground(new java.awt.Color(0, 74, 163));
        tbGerbong.setShowHorizontalLines(false);
        tbGerbong.setShowVerticalLines(false);
        tbGerbong.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbGerbong);
        if (tbGerbong.getColumnModel().getColumnCount() > 0) {
            tbGerbong.getColumnModel().getColumn(0).setResizable(false);
            tbGerbong.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbGerbong.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbGerbong.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbGerbong.getColumnModel().getColumn(3).setPreferredWidth(150);
            tbGerbong.getColumnModel().getColumn(4).setResizable(false);
            tbGerbong.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 42, 113));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Kereta");

        txtIDKeretaGerbong.setBackground(new java.awt.Color(0, 42, 113));
        txtIDKeretaGerbong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDKeretaGerbong.setForeground(new java.awt.Color(255, 255, 255));
        txtIDKeretaGerbong.setBorder(null);
        txtIDKeretaGerbong.setCaretColor(new java.awt.Color(255, 0, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Gerbong");

        txtID_Gerbong.setBackground(new java.awt.Color(0, 42, 113));
        txtID_Gerbong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID_Gerbong.setForeground(new java.awt.Color(255, 255, 255));
        txtID_Gerbong.setBorder(null);
        txtID_Gerbong.setCaretColor(new java.awt.Color(255, 0, 51));

        txtNomorGerbong.setBackground(new java.awt.Color(0, 42, 113));
        txtNomorGerbong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomorGerbong.setForeground(new java.awt.Color(255, 255, 255));
        txtNomorGerbong.setBorder(null);
        txtNomorGerbong.setCaretColor(new java.awt.Color(255, 0, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nomor");

        txtKapasitasGerbong.setBackground(new java.awt.Color(0, 42, 113));
        txtKapasitasGerbong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKapasitasGerbong.setForeground(new java.awt.Color(255, 255, 255));
        txtKapasitasGerbong.setBorder(null);
        txtKapasitasGerbong.setCaretColor(new java.awt.Color(255, 0, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kapasitas");

        btnInsertGerbong.setBackground(new java.awt.Color(0, 74, 163));
        btnInsertGerbong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsertGerbong.setForeground(new java.awt.Color(204, 255, 255));
        btnInsertGerbong.setText("Insert");
        btnInsertGerbong.setBorder(null);
        btnInsertGerbong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsertGerbongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertGerbongMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInsertGerbongMouseReleased(evt);
            }
        });

        btnUpdateGerbong.setBackground(new java.awt.Color(0, 74, 163));
        btnUpdateGerbong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateGerbong.setForeground(new java.awt.Color(204, 255, 255));
        btnUpdateGerbong.setText("Update");
        btnUpdateGerbong.setBorder(null);
        btnUpdateGerbong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateGerbongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateGerbongMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUpdateGerbongMouseReleased(evt);
            }
        });

        btnDeleteGerbong.setBackground(new java.awt.Color(0, 74, 163));
        btnDeleteGerbong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteGerbong.setForeground(new java.awt.Color(204, 255, 255));
        btnDeleteGerbong.setText("Delete");
        btnDeleteGerbong.setBorder(null);
        btnDeleteGerbong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteGerbongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteGerbongMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteGerbongMouseReleased(evt);
            }
        });

        btnResetGerbong.setBackground(new java.awt.Color(0, 74, 163));
        btnResetGerbong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetGerbong.setForeground(new java.awt.Color(204, 255, 255));
        btnResetGerbong.setText("Reset");
        btnResetGerbong.setBorder(null);
        btnResetGerbong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetGerbongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetGerbongMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnResetGerbongMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomorGerbong)
                            .addComponent(jSeparator3)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKapasitasGerbong)
                            .addComponent(jSeparator4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnInsertGerbong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDKeretaGerbong)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addComponent(txtID_Gerbong)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnUpdateGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResetGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDKeretaGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtID_Gerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNomorGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKapasitasGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        jPanel5.setBackground(new java.awt.Color(0, 42, 113));

        btnNextGerbong.setBackground(new java.awt.Color(0, 74, 163));
        btnNextGerbong.setPreferredSize(new java.awt.Dimension(80, 44));
        btnNextGerbong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextGerbongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextGerbongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNextGerbongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNextGerbongMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Next");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout btnNextGerbongLayout = new javax.swing.GroupLayout(btnNextGerbong);
        btnNextGerbong.setLayout(btnNextGerbongLayout);
        btnNextGerbongLayout.setHorizontalGroup(
            btnNextGerbongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnNextGerbongLayout.setVerticalGroup(
            btnNextGerbongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnFirstGerbong.setBackground(new java.awt.Color(0, 74, 163));
        btnFirstGerbong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFirstGerbongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFirstGerbongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFirstGerbongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFirstGerbongMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("First");

        javax.swing.GroupLayout btnFirstGerbongLayout = new javax.swing.GroupLayout(btnFirstGerbong);
        btnFirstGerbong.setLayout(btnFirstGerbongLayout);
        btnFirstGerbongLayout.setHorizontalGroup(
            btnFirstGerbongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnFirstGerbongLayout.setVerticalGroup(
            btnFirstGerbongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnLastGerbong.setBackground(new java.awt.Color(0, 74, 163));
        btnLastGerbong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLastGerbongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLastGerbongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLastGerbongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLastGerbongMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Last");

        javax.swing.GroupLayout btnLastGerbongLayout = new javax.swing.GroupLayout(btnLastGerbong);
        btnLastGerbong.setLayout(btnLastGerbongLayout);
        btnLastGerbongLayout.setHorizontalGroup(
            btnLastGerbongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnLastGerbongLayout.setVerticalGroup(
            btnLastGerbongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnPrevGerbong.setBackground(new java.awt.Color(0, 74, 163));
        btnPrevGerbong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrevGerbongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrevGerbongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrevGerbongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPrevGerbongMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Prev");

        javax.swing.GroupLayout btnPrevGerbongLayout = new javax.swing.GroupLayout(btnPrevGerbong);
        btnPrevGerbong.setLayout(btnPrevGerbongLayout);
        btnPrevGerbongLayout.setHorizontalGroup(
            btnPrevGerbongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnPrevGerbongLayout.setVerticalGroup(
            btnPrevGerbongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFirstGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLastGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLastGerbong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFirstGerbong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNextGerbong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPrevGerbong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstGerbongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstGerbongMouseEntered
        btnFirstGerbong.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnFirstGerbongMouseEntered

    private void btnFirstGerbongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstGerbongMouseExited
        btnFirstGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnFirstGerbongMouseExited

    private void btnFirstGerbongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstGerbongMousePressed
        btnFirstGerbong.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnFirstGerbongMousePressed

    private void btnFirstGerbongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstGerbongMouseReleased
        btnFirstGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnFirstGerbongMouseReleased

    private void btnPrevGerbongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevGerbongMouseEntered
        btnPrevGerbong.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnPrevGerbongMouseEntered

    private void btnPrevGerbongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevGerbongMouseExited
        btnPrevGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnPrevGerbongMouseExited

    private void btnPrevGerbongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevGerbongMousePressed
        btnPrevGerbong.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnPrevGerbongMousePressed

    private void btnPrevGerbongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevGerbongMouseReleased
        btnPrevGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnPrevGerbongMouseReleased

    private void btnNextGerbongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextGerbongMouseEntered
        btnNextGerbong.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnNextGerbongMouseEntered

    private void btnNextGerbongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextGerbongMouseExited
        btnNextGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnNextGerbongMouseExited

    private void btnNextGerbongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextGerbongMousePressed
        btnNextGerbong.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnNextGerbongMousePressed

    private void btnNextGerbongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextGerbongMouseReleased
        btnNextGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnNextGerbongMouseReleased

    private void btnLastGerbongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastGerbongMouseEntered
        btnLastGerbong.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnLastGerbongMouseEntered

    private void btnLastGerbongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastGerbongMouseExited
        btnLastGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnLastGerbongMouseExited

    private void btnLastGerbongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastGerbongMousePressed
        btnLastGerbong.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnLastGerbongMousePressed

    private void btnLastGerbongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastGerbongMouseReleased
        btnLastGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnLastGerbongMouseReleased

    private void btnInsertGerbongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertGerbongMouseEntered
        if (btnInsertGerbong.isEnabled()) {
            btnInsertGerbong.setBackground(new Color(47, 71, 194));
        } else if(!btnInsertGerbong.isEnabled()){
            btnInsertGerbong.setBackground(new Color(0,74,163));
        }
    }//GEN-LAST:event_btnInsertGerbongMouseEntered

    private void btnInsertGerbongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertGerbongMouseExited
        btnInsertGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnInsertGerbongMouseExited

    private void btnInsertGerbongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertGerbongMouseReleased
        btnInsertGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnInsertGerbongMouseReleased

    private void btnUpdateGerbongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateGerbongMouseEntered
        if (btnUpdateGerbong.isEnabled()) {
            btnUpdateGerbong.setBackground(new Color(47, 71, 194));
        } else if(!btnUpdateGerbong.isEnabled()){
            btnUpdateGerbong.setBackground(new Color(0,74,163));
        }
    }//GEN-LAST:event_btnUpdateGerbongMouseEntered

    private void btnUpdateGerbongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateGerbongMouseExited
        btnUpdateGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnUpdateGerbongMouseExited

    private void btnUpdateGerbongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateGerbongMouseReleased
        btnUpdateGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnUpdateGerbongMouseReleased

    private void btnDeleteGerbongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteGerbongMouseEntered
        if (btnDeleteGerbong.isEnabled()) {
            btnDeleteGerbong.setBackground(new Color(47, 71, 194));
        } else if(!btnDeleteGerbong.isEnabled()){
            btnDeleteGerbong.setBackground(new Color(0,74,163));
        }
    }//GEN-LAST:event_btnDeleteGerbongMouseEntered

    private void btnDeleteGerbongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteGerbongMouseExited
        btnDeleteGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnDeleteGerbongMouseExited

    private void btnDeleteGerbongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteGerbongMouseReleased
        btnDeleteGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnDeleteGerbongMouseReleased

    private void btnResetGerbongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetGerbongMouseEntered
        if (btnResetGerbong.isEnabled()) {
            btnResetGerbong.setBackground(new Color(47, 71, 194));
        } else if(!btnResetGerbong.isEnabled()){
            btnResetGerbong.setBackground(new Color(0,74,163));
        }
    }//GEN-LAST:event_btnResetGerbongMouseEntered

    private void btnResetGerbongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetGerbongMouseExited
        btnResetGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnResetGerbongMouseExited

    private void btnResetGerbongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetGerbongMouseReleased
        btnResetGerbong.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnResetGerbongMouseReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        jLabel1.setOpaque(true);
        jLabel1.setBackground(new Color(0,30,84));
        txtIDKeretaGerbong.setText("");
        txtID_Gerbong.setText("");
        txtNomorGerbong.setText("");
        txtKapasitasGerbong.setText("");
        txtID_Gerbong.setEditable(true);
        btnUpdateGerbong.setEnabled(false);
        btnDeleteGerbong.setEnabled(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setOpaque(true);
        jLabel1.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setOpaque(true);
        jLabel1.setBackground(new Color(0,30,84));
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerbong_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerbong_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerbong_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerbong_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerbong_Menu().setVisible(true);
            }
        });
    }
    
    public JButton getBtnInsertGerbong(){
        return btnInsertGerbong;
    }
    
    public JButton getBtnUpdateGerbong(){
        return btnUpdateGerbong;
    }
    
    public JButton getBtnDeleteGerbong(){
        return btnDeleteGerbong;
    }
    
    public JButton getBtnResetGerbong(){
        return btnResetGerbong;
    }
    
    public JPanel getBtnFirstGerbong(){
        return btnFirstGerbong;
    }
    
    public JPanel getBtnNextGerbong(){
        return btnNextGerbong;
    }
    
    public JPanel getBtnPrevGerbong(){
        return btnPrevGerbong;
    }
    
    public JPanel getBtnLastGerbong(){
        return btnLastGerbong;
    }
    
    public JTable getTBgerbong(){
        return tbGerbong;
    }
    
    public JTextField getTXTID_Gerbong(){
        return txtID_Gerbong;
    }
    
    public JTextField getTXTID_Kereta(){
        return txtIDKeretaGerbong;
    }
    
    public JTextField getTXTNomorgerbong(){
        return txtNomorGerbong;
    }
    
    public JTextField getTXTKapasitasGerbong(){
        return txtKapasitasGerbong;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteGerbong;
    private javax.swing.JPanel btnFirstGerbong;
    private javax.swing.JButton btnInsertGerbong;
    private javax.swing.JPanel btnLastGerbong;
    private javax.swing.JPanel btnNextGerbong;
    private javax.swing.JPanel btnPrevGerbong;
    private javax.swing.JButton btnResetGerbong;
    private javax.swing.JButton btnUpdateGerbong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tbGerbong;
    private javax.swing.JTextField txtIDKeretaGerbong;
    private javax.swing.JTextField txtID_Gerbong;
    private javax.swing.JTextField txtKapasitasGerbong;
    private javax.swing.JTextField txtNomorGerbong;
    // End of variables declaration//GEN-END:variables
}
